homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('project/', views.project, name='project'),
    path('putschedule/', views.putschedule, name='putschedule'),
    path('schedule/', views.thanks, name='schedule'),
    path('delete/<int:id>', views.delete, name='delete')
]

scheduling/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('putschedule/', views.putschedule, name='putschedule'),
    path('schedule/', views.thanks, name='thanks'),
    path('delete/<int:id>', views.delete, name='delete')
]

showdown/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django import forms
from django.utils import timezone

# Create your models here.
class Reminder(models.Model):
    name = models.CharField(max_length=2147483647, default='')
    date = models.DateField()
    time = models.TimeField(help_text='HH:MM AM/PM', default=timezone.now())
    location = models.CharField(max_length=2147483647, default='')
    category = models.CharField(max_length=2147483647, default='')

scheduling/models.py
from django.db import models
from django import forms
from django.utils import timezone

# Create your models here.
class Reminder(models.Model):
    name = models.CharField(max_length=2147483647, default='')
    date = models.DateField()
    time = models.TimeField(help_text='HH:MM AM/PM', default=timezone.now())
    location = models.CharField(max_length=2147483647, default='')
    category = models.CharField(max_length=2147483647, default='')

homepage/forms.py
from django import forms
from .models import Reminder

class ReminderForm(forms.ModelForm):
    class Meta:
        model = Reminder
        fields = '__all__'
        widgets = {\
            'date' : forms.DateInput(attrs={'type':'date'}),
            'time' : forms.TimeInput(attrs={'type':'time'}),
            }
    pass

scheduling/forms.py
from django import forms
from .models import Reminder

class ReminderForm(forms.ModelForm):
    class Meta:
        model = Reminder
        fields = '__all__'
        widgets = {\
            'date' : forms.DateInput(attrs={'type':'date'}),
            'time' : forms.TimeInput(attrs={'type':'time'}),
            }
    pass

homepage/views.py
from django.shortcuts import render
from .forms import ReminderForm
from .models import Reminder
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, "index.html")

def gallery(request):
    return render(request, "gallery.html")

def project(request):
    return render(request, "project.html")

def putschedule(request):
    if request.method == 'POST':
        jadwal = ReminderForm(request.POST)

        if jadwal.is_valid():
            jadwal.save()

            return HttpResponseRedirect(reverse('thanks'))
        else:
            return render(request, 'putschedule.html',\
                {
                    'navigate' : '',
                    'form' : jadwal,
                    'targets' : {
                        'Home' : 'homepage:index',
                        'Schedule' : 'homepage:thanks',
                    }
                })

    return render(request, 'putschedule.html',\
        {
            'navigate' : '',
            'form' : ReminderForm,
            'targets' : {
                'Home' : 'homepage:index',
                'Schedule' : 'homepage:thanks',
            }
        })

def thanks(request):
    jadwal = Reminder.objects.all()
    return render(request, 'response/thanks.html',
        {
            'schedule_data' : jadwal,
            'targets' : {
                'Home' : 'homepage:index',
                'Put Schedule' : 'homepage:putschedule',
            },
        })

def delete(request, id):
    jadwal = Reminder.objects.get(pk=id)
    jadwal.delete()
    return HttpResponseRedirect(reverse('thanks'))

scheduling/views.py
from django.shortcuts import render
from .forms import ReminderForm
from .models import Reminder
from django.http import HttpResponseRedirect
from django.urls import reverse

targets = {'Schedule' : 'thanks', 'Put Schedule' : 'putschedule'}

# Create your views here.

def putschedule(request):
    if request.method == 'POST':
        jadwal = ReminderForm(request.POST)

        if jadwal.is_valid():
            jadwal.save()

            return HttpResponseRedirect(reverse('thanks'))
        else:
            return render(request, 'putschedule.html',\
                {
                    'navigate' : '',
                    'form' : jadwal,
                    'targets' : {
                        'Schedule' : 'thanks'
                    }
                })

    return render(request, 'putschedule.html',\
        {
            'navigate' : '',
            'form' : ReminderForm,
            'targets' : {
                'Schedule' : 'thanks'
            }
        })

def thanks(request):
    jadwal = Reminder.objects.all()
    return render(request, 'response/thanks.html',
        {
            'schedule_data' : jadwal,
            'targets' : {
                'Put Schedule' : 'putschedule'
            },
        })

def delete(request, id):
    jadwal = Reminder.objects.get(pk=id)
    jadwal.delete()
    return HttpResponseRedirect(reverse('thanks'))

homepage/templates/base/bootlink.html
<!-- bootstrap template link -->
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap-grid.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap-reboot.css' %}>

homepage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>This is title</title>
    <link rel="stylesheet" href={% static 'css/bootstrap-grid.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap-reboot.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
    <link rel="stylesheet" href={% static 'css/profiler.css' %}>
</head>

<body>
    <div class="row header">
        <img class="header-image" src={% static 'assets/Together.png' %}>
    </div>
    <div class="row header text-tab">
        <div class="col-4"></div>
        <div class="col-6">
            <a href={% url 'homepage:gallery' %}>GALLERY</a>
            <a href={% url 'homepage:project' %}>PROJECT</a>
            <a href={% url 'homepage:schedule' %}>SCHEDULE</a>
            <a href=>NEWLY</a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2 col-1"></div>
        <div class="col-lg-2 col-3 shift">
            <div class="row">
                <a href={% url 'homepage:index' %}><img class="rounding" src={% static 'assets/profile_picture.png' %}></a>
            </div>
        </div>
    </div>
    <div class="row shift" style="padding-top: 50px">
        <div class="col-1"></div>
        <div class="col-10 card-list shift">
            <div id="columns">
                <imgcard><img class="gallery-frame" src={% static 'assets/gallery/backdest-r.jpg' %}></imgcard>
                <imgcard><img class="gallery-frame" src={% static 'assets/gallery/kr.jpg' %}></imgcard>
                <imgcard><img class="gallery-frame" src={% static 'assets/gallery/desert fight.jpg' %}></imgcard>
                <imgcard><img class="gallery-frame" src={% static 'assets/gallery/mia_sitting_on_fence_2.jpg' %}></imgcard>
                <imgcard><img class="gallery-frame" src={% static 'assets/gallery/deserting.jpg' %}></imgcard>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>This is title</title>
    <link rel="stylesheet" href={% static 'css/bootstrap-grid.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap-reboot.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
    <link rel="stylesheet" href={% static 'css/profiler.css' %}>
</head>

<body>
    <div class="row header">
        <img class="header-image" src={% static 'assets/Together.png' %}>
    </div>
    <div class="row header text-tab">
        <div class="col-4"></div>
        <div class="col-6">
            <a href={% url 'homepage:gallery' %}>GALLERY</a>
            <a href={% url 'homepage:project' %}>PROJECT</a>
            <a href={% url 'homepage:schedule' %}>SCHEDULE</a>
            <a href=>NEWLY</a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2 col-1"></div>
        <div class="col-lg-2 col-3 shift">
            <div class="row">
                <a href={% url 'homepage:index' %}><img class="rounding" src={% static 'assets/profile_picture.png' %}></a>
            </div>
            <div class="row text-card text-size-1">
                <p class="col">
                    <br>
                    Qadzif Kamil Zahari<br>
                    1806205565<br>
                    2018<br>
                    <br>
                    <br>
                    <br>
                    Surel : qadzifi@gmail.com
                </p>
            </div>
        </div>
        <div class="col-lg-6 col-7 card-list shift">
            <div class="card card-body-cs card-pad text-size-1">
                <b class="card-center text-card">
                    The boring artist that's master of all jack of none <br>
                </b>
            </div>
            <br>
            <div class="card card-body-cs card-pad text-size-1">
                <p class="card-center text-card" style="font-size: 40px;">
                    Skills<br>
                </p>
                <div class="row">
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-1.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-2.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-3.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-4.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-5.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-6.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-7.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-8.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-9.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-10.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-11.png' %}></div>
                    <div class="col-lg-2 col-md-3 col-4 skill-container"><img class="skill" src={% static 'assets/skils/image-12.png' %}></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row shift" style="padding-top: 50px">
        <div class="col-sm-4"></div>
        <div class="col-sm-2"></div>
    </div>
</body>
</html>

homepage/templates/nav/list.html
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/navtab.css' %}>
{% include 'base/bootlink.html' %}
<div class="nav-bar">
    <h1>
        {% for key, val in targets.items %}
        <a href={% url val %} class="nav-card" style="color: white;">{{ key }}</a>
        {% endfor %}
    </h1><br>
</div>

homepage/templates/newly.html
<!DOCTYPE html>
<html>
<head>
    <title>This is title</title>
    <link rel="stylesheet" href="./css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="./css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/profiler.css">
</head>

<body>
    <div class="row header">
        <img class="header-image" src="./assets/Together.png">
    </div>
    <div class="row header text-tab">
        <div class="col-sm-4"></div>
        <div class="col-sm-1">
            <a href="gallery.html">GALLERY</a>
        </div>
        <div class="col-sm-1">
            <a href="project.html">PROJECT</a>
        </div>
        <div class="col-sm-1">
            <a href="newly.html">NEWLY</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-2 shift">
            <div class="row">
                <a href="index.html"><img class="rounding" src="./assets/profile_picture.png"></a>
            </div>
        </div>
        <div class="col-sm-6 card-list shift text-card">
            Sorry, this page is under construction
        </div>
    </div>
    <div class="row shift" style="padding-top: 50px">
        <div class="col-sm-4"></div>
        <div class="col-sm-2"></div>
    </div>
</body>
</html>

homepage/templates/project.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>This is title</title>
    <link rel="stylesheet" href={% static 'css/bootstrap-grid.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap-reboot.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
    <link rel="stylesheet" href={% static 'css/profiler.css' %}>
</head>

<body>
    <div class="row header">
        <img class="header-image" src={% static 'assets/Together.png' %}>
    </div>
    <div class="row header text-tab">
        <div class="col-4"></div>
        <div class="col-6">
            <a href={% url 'homepage:gallery' %}>GALLERY</a>
            <a href={% url 'homepage:project' %}>PROJECT</a>
            <a href={% url 'homepage:schedule' %}>SCHEDULE</a>
            <a href=>NEWLY</a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2 col-1"></div>
        <div class="col-lg-2 col-3 shift">
            <div class="row">
                <a href={% url 'homepage:index' %}><img class="rounding" src={% static 'assets/profile_picture.png' %}></a>
            </div>
        </div>
    </div>
    <div class="row shift" style="padding-top: 50px">
        <div class="col-lg-2 col-1"></div>
        <div class="col-lg-8 col-10 card-list shift text-size-1">
            <div class="card card-body-cs card-pad text-card">
                <b class="card-title">
                    <a href="https://github.com/qadzifi/datapack-helper-edit">Datapack Helper Custom</a><br>
                </b>
                <p>
                    VSCode plugin for making datapack in Minecraft<br>
                    Customized version from <a href="https://github.com/pca006132/datapack-helper">github.com/pca006132/datapack-helper</a>
                </p>
            </div>
            <br>
            <div class="card card-body-cs card-pad text-card">
                <b class="card-title">
                    <a href="https://github.com/qadzifi/KIR-kelas-xi">Aplikasi Visual Grafik Irisan Kerucut</a><br>
                </b>
                <p>
                    Aplikasi untuk menampilkan grafik irisan kerucut<br>
                    Dibuat dalam rangka mata pelajaran KIR
                </p>
            </div>
        </div>
        <div class="col-lg-2 col-1"></div>
    </div>
</body>
</html>

homepage/templates/putschedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include 'base/bootlink.html' %}
    <link rel="stylesheet" type="text/css" href={% static 'css/scheduling.css' %}>
</head>
<body id="body">
    {% include 'nav/list.html' with targets=targets %}
    <div class="row">
        <div class="w-25"></div>
        <div class="w-50">
            <div class="text-center-v"><b>Input schedule</b></div>
            <form action={% url 'homepage:putschedule' %} method="POST">
                {% csrf_token %}
                <table class="center-vertical">
                    <tr>
                        <th>Label</th>
                        <th>Value</th>
                    </tr>
                    {{ form.as_table }}
                </table>
                <input class="center-vertical" type="submit" value="submit">
            </form>
        </div>
        <div class="w-25"></div>
    </div>
</body>
</html>

homepage/templates/response/thanks.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include 'base/bootlink.html' %}
    <link rel="stylesheet" type="text/css" href={% static 'css/scheduling.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'css/navtab.css' %}>
</head>
<body id="body">
    {% include 'nav/list.html' with targets=targets %}
    <div class="text-center-v"><h1>This is your schedule</h1></div>
    
    <table class="center-vertical">
        <tr>
            <td>Nama</td>
            <td>Tanggal</td>
            <td>Jam</td>
            <td>Lokasi</td>
            <td>Kategori</td>
            <td></td>
        </tr>
        {% if schedule_data %}
            {% for schedule in schedule_data %}
            <tr>
                <td><b>{{schedule.name}}</b></td>
                <td><b>{{schedule.date}}</b></td>
                <td><b>{{schedule.time}}</b></td>
                <td><b>{{schedule.location}}</b></td>
                <td><b>{{schedule.category}}</b></td>
                <td><a href={% url 'delete' schedule.id %} style="color: white;"><div class="nav-card text-center-v">Delete</div></a></td>
            </tr>
            {% endfor %}
                
        {% endif %}
    </table>
</body>
</html>

scheduling/templates/base/bootlink.html
<!-- bootstrap template link -->
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap-grid.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap-reboot.css' %}>

scheduling/templates/nav/list.html
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/navtab.css' %}>
{% include 'base/bootlink.html' %}
<div class="nav-bar">
    <h1>
        {% for key, val in targets.items %}
        <a href={% url val %} class="nav-card" style="color: white;">{{ key }}</a>
        {% endfor %}
    </h1><br>
</div>

scheduling/templates/putschedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include 'base/bootlink.html' %}
    <link rel="stylesheet" type="text/css" href={% static 'css/scheduling.css' %}>
</head>
<body id="body">
    {% include 'nav/list.html' with targets=targets %}
    <div class="row">
        <div class="w-25"></div>
        <div class="w-50">
            <div class="text-center-v"><b>Input schedule</b></div>
            <form action={% url 'putschedule' %} method="POST">
                {% csrf_token %}
                <table class="center-vertical">
                    <tr>
                        <th>Label</th>
                        <th>Value</th>
                    </tr>
                    {{ form.as_table }}
                </table>
                <input class="center-vertical" type="submit" value="submit">
            </form>
        </div>
        <div class="w-25"></div>
    </div>
</body>
</html>

scheduling/templates/response/thanks.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include 'base/bootlink.html' %}
    <link rel="stylesheet" type="text/css" href={% static 'css/scheduling.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'css/navtab.css' %}>
</head>
<body id="body">
    {% include 'nav/list.html' with targets=targets %}
    <div class="text-center-v"><h1>This is your schedule</h1></div>
    
    <table class="center-vertical">
        <tr>
            <td>Nama</td>
            <td>Tanggal</td>
            <td>Jam</td>
            <td>Lokasi</td>
            <td>Kategori</td>
            <td></td>
        </tr>
        {% if schedule_data %}
            {% for schedule in schedule_data %}
            <tr>
                <td><b>{{schedule.name}}</b></td>
                <td><b>{{schedule.date}}</b></td>
                <td><b>{{schedule.time}}</b></td>
                <td><b>{{schedule.location}}</b></td>
                <td><b>{{schedule.category}}</b></td>
                <td><a href={% url 'delete' schedule.id %} style="color: white;"><div class="nav-card text-center-v">Delete</div></a></td>
            </tr>
            {% endfor %}
                
        {% endif %}
    </table>
</body>
</html>